# Generated by Django 5.1.6 on 2026-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_emaillog_task_id_alter_emaillog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
