# Generated by Django 5.1.6 on 2026-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_emaillog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='error',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
