# Generated by Django 5.1.6 on 2026-01-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_remove_emaillog_error_emaillog_email_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='follow_up_done',
            field=models.BooleanField(default=False),
        ),
    ]
