# Generated by Django 5.1.6 on 2026-01-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_emaillog_follow_up_at_emaillog_follow_up_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'failed')], default='PENDING', max_length=20),
        ),
    ]
