# Generated by Django 5.1.6 on 2026-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_alter_emaillog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
