# Generated by Django 5.1.6 on 2026-01-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_suppressedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
